config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  root 'articles#index'

  resources :users, only: [:show,:edit,:update,] do
    member do
      get 'out'
      patch 'withdraw'
    end
    collection do
      get 'favorites'
    end
  end

  resources :articles do
    collection do
      get 'search'
      get 'rank'
      get 'map'
    end
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:index, :create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :image

  #検索機能（都道府県）
  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  with_options presence: true do
    validates :title
    validates :postal_code
    validates :prefecture_code
    validates :city
    validates :street
    validates :telephone_number
    validates :url
  end

  # ユーザーが「いいね」を押しているかどうかを判別する
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 'address'にまとめ
  def address
    self.prefecture_code + self.city + self.street + self.other_address
  end

  # カラムのデータをaddressという変数にまとめる
  def address
    [self.prefecture_code,self.city,self.street].compact.join()
  end
  # addressを登録した際にgeocoderが緯度、経度のカラムにも自動的に値を入れてくれる
  geocoded_by :address
  after_validation :geocode

  #レビューの平均（starマーク）
  def avg_score
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f
    else
      0.0
    end
  end

  #レビューの平均点
  def review_score_percentage
    unless self.reviews.empty?
      reviews.average(:score).round(1).to_f*100/5
    else
      0.0
    end
  end

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates_uniqueness_of :article_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :user
  belongs_to :article

  validates :score, presence: true
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image

  has_many :articles
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy


  validates :name, presence: true

  #ログイン時に退会済みのユーザーが同じアカウントでログイン出来ないようにする。
  # true = ログインユーザーが有効な状態（退会していない）
  def active_for_authentication?
    super && (self.is_valid == true)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configer_permitted_parameters, if: :devise_controller?

  before_action :set_search

  protected

  def after_sign_in_path_for(recource)
    articles_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configer_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:telephone_number])
  end
  
  private
  
  def set_search
    @search = Article.ransack(params[:q])
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #非ログインユーザーへのアクセス制限
  before_action :authenticate_user!, except: [:index,:show, :search, :rank, :favorites]

  #ワードで検索機能
  before_action :set_search

  def index
    @articles = Article.all
    @articles = Article.page(params[:page]).per(9)
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id  #誰が投稿するのか
    if @article.save
      redirect_to article_path(@article), notice: '投稿が追加されました'
    else
      render :new
    end
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
    @review = Review.new
    gon.article = @article
  end

  def edit
    @article = Article.find(params[:id])
    if @article.user != current_user
      redirect_to articles_path, alert: '不正なアクセスです'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
    redirect_to article_path(@article), notice: '内容が変更されました'
    else
      render :edit
    end
  end

  def destroy
    article = Article.find(params[:id])
    article.destroy
    redirect_to user_path(article.user), notice: '投稿を削除しました'
  end

  #検索機能
  def search
    @results = @search.result
  end

  def rank
     # イイね順にランキング形式で表示する
    @all_ranks = Article.find(Favorite.group(:article_id).order('count(article_id) desc').limit(9).pluck(:article_id))
  end

  # 現在地から検索
  def map
    gon.articles = Article.all
  end

  private


  #ransackメソッド:送られてきたパラメーターを元にテーブルからデータを検索するメソッド
  #resultメソッド:ransackメソッドで取得したデータを
  #ActiveRecord_Relationのオブジェクトに変換するメソッド
  def set_search
    @search = Article.ransack(params[:q])
  end

  def article_params
    params.require(:article).permit(:title,:image,:postal_code,:prefecture_code,:city,:street,:other_address,:url,:introduction,:telephone_number)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @article = Article.find(params[:article_id])
    favorite = current_user.favorites.build(article_id: params[:article_id])
    favorite.save
  end

  def destroy
    @article = Article.find(params[:article_id])
    favorite = Favorite.find_by(article_id: params[:article_id], user_id: current_user.id)
    favorite.destroy
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :authenticate_user!, only: [:create]

  def index
    @article = Article.find(params[:article_id])
    @reviews = @article.reviews
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      redirect_to article_reviews_path(@review.article)
    else
      @article = Article.find(params[:id])
      render "article/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:article_id, :score, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:show]

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to articles_path, alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    flash[:success] = "登録情報を変更しました"
    redirect_to user_path(@user)
  end

  def out
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to articles_path, alert: '不正なアクセスです'
    end
  end

  def withdraw
    @user = User.find(params[:id])
    @user.update(is_valid: false)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end
  
  def favorites
    
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        編集ページ
      </h1>
    </div>
  </div>
</section>

<% if @article.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @article, local: true do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :postal_code, "郵便番号", class: "label" %><br>
            <%= f.text_field :postal_code, autocomplete: "postal_code", id: "article_postal_code" %>
          </div>

          <div class="field">
            <%= f.label :prefecture_code, "都道府県", class: "label" %><br>
            <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all,  :name, :name, autocomplete: "prefecture_code", id: "article_prefecture_code" %>
          </div>

          <div class="field">
            <%= f.label :city, "ご住所１（市区町村）", class: "label" %><br>
            <%= f.text_field :city, autocomplete: "city", id: "article_city"  %>
          </div>

          <div class="field">
            <%= f.label :street, "ご住所２（町名、番地）", class: "label" %><br>
            <%= f.text_field :street, autocomplete: "street", id: "article_street"  %>
          </div>

          <div class="field">
            <%= f.label :other_address, "その他", class: "label" %><br>
            <%= f.text_field :other_address, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :telephone_number, "電話番号", class: "label" %>
            <%= f.text_field :telephone_number, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :url, "ホームページ", class: "label" %>
            <%= f.text_field :url, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :introduction, "補足", class: "label" %>
            <%= f.text_area :introduction, class: "textarea" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/articles/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        みんなの♨ゆ️♨️
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @articles.each do |article| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to article_path(article) do %>
                  <%= attachment_image_tag article, :image, format: 'jpeg', size: "100x100", fallback: "no-image_article.jpeg" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title">
                    <%= link_to article_path(article) do%>
                    <%= article.title %>
                    <% end %>
                  </div>
                  <i class="fas fa-heart"></i>
                  <%= article.favorites.count %>
                </div>
              </div>

            <div class="content average-score">
              <div class="star-rating mb-2">
                <div class="star-rating-front" style="width: <%= article.review_score_percentage %>%">★★★★★</div>
                <div class="star-rating-back">★★★★★</div>
              </div>
              <div class="average-score-display ml-3 pt-2">
                <%= article.avg_score %>点（<%= article.reviews.count %>件のレビュー）
              </div>
            </div>
              <div class='card-footer'>
                <%= link_to article_reviews_path(article), class: "button card-footer-item" do %>
                口コミを見る
                <% end %>
                <%= link_to article_path(article), class: "button card-footer-item" do %>
                口コミを書く
                <% end %>
              </div>

              <div class="content">
                <time><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新日
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <%= paginate(@articles) %>
</section>

app/views/articles/map.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ♨周辺施設を探す♨
      </h1>
    </div>
  </div>
</section>


  <div class="col-lg-12">
    <div class="card map-card">
      <div class="card-img-bottom">
        <div id="map"></div>
      </div>
    </div>
  </div>




<div id="map"></div>


<script>
let map;
let marker = []; // マーカーを複数表示させたいので、配列化
let infoWindow = []; // 吹き出しを複数表示させたいので、配列化
const articles = gon.articles; // コントローラーで定義したインスタンス変数を変数に代入

function initMap(){
  // 現在位置の特定
  navigator.geolocation.getCurrentPosition(function (position){
    // LatLngに位置座標を代入
    LatLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

    // mapの初期位置設定
    map = new google.maps.Map(document.getElementById('map'), {
      center: LatLng,
      zoom: 13
    });
    // map.setCenterで地図が初期位置に移動
    map.setCenter(LatLng);

    // forは繰り返し処理
    // 変数iを0と定義し、
    // その後gonで定義したarticles分繰り返し加える処理を行う
    for (let i = 0; i < articles.length; i++){
      // articles[i]は変数iのユーザーを取得している
      marker[i] = new google.maps.Marker({
        map: map,
        position: {
          // DBに保存してある、緯度・経度を呼び出す
          lat: articles[i].latitude,
          lng: articles[i].longitude
        }
      });

      // 変数iを変数idに代入
      let id = articles[i]['id']

      // infoWindowは吹き出し
      infoWindow[i] = new google.maps.InfoWindow({
        // contentで中身を指定
        // 文字にリンクを貼り付けた形で表示
        content: `<a href='/articles/${id}'>${articles[i].title}</a>`
      });
      // markerがクリックされた時、
      marker[i].addListener("click", function(){
        // infoWindowを表示
        infoWindow[i].open(map, marker[i]);
      });
    }
  });
}
</script>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap">
</script>

app/views/articles/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ♨️施設詳細♨️
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <div class="card">
          <div class="card-image">
            <figure class="image is-4by3">
              <%= attachment_image_tag @article, :image, fallback: "no-image_article.jpeg" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <h4>施設名</h4>
                <p class="title is-4"><%= @article.title %></p>
              </div>
              <!-- いいね機能 Ajax -->
              <div id="favorites_buttons_<%= @article.id %>">
                <%= render partial: 'favorites/favorite', locals: { article: @article} %>
              </div>
              <!--ここまで -->
            </div>
            <div class="media">
              <div class="media-content">
                <h4>住所</h4>
                <p class="title is-4">〒<%=@article.postal_code %> <br>
                <%= @article.address %></p>
              </div>
            </div>
            <div class="media">
              <div class="media-content">
                <h4>電話番号</h4>
                <p class="title is-4"><%= @article.telephone_number %></p>
              </div>
            </div>
            <div class="media">
              <div class="media-content">
                ホームページ
                <p class="title is-4"><%= raw Rinku.auto_link(h(@article.url)) %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>補足</th>
                </tr>
                <tr>
                  <td><%= simple_format @article.introduction %></td>
                </tr>
              </table>
              <% if user_signed_in? %>
              <% if @article.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_article_path(@article), class: "button is-success" %>
              <% end %>
              <% end %>
            </div>
            <div class="card-content">
              <div class="content average-score">
                <div class="star-rating mb-2">
                 <div class="star-rating-front" style="width: <%= @article.review_score_percentage %>%">★★★★★</div>
                 <div class="star-rating-back">★★★★★</div>
                </div>
                <div class="average-score-display ml-3 pt-2">
                  <%= @article.avg_score %>点（<%= @article.reviews.count %>件のレビュー）
                </div>
              </div>
              <%= render 'reviews/form', review: @review, article: @article %>
            </div>
          </div>
        </div>
      </div>


    </div>
  </div>
</section>

<section class='map section'>
  <div class='map container'>
    <div class='columns is-centered'>
      <div class='column is-7'>
              <div id="map"></div>


      <script>
      let map;

      function initMap() {
      // geocoderを初期化
      geocoder = new google.maps.Geocoder()

      map = new google.maps.Map(document.getElementById('map'), {
        // コントローラーで定義した変数から緯度経度を呼び出し、マップの中心に表示
        center: {
          lat: gon.article.latitude,
          lng: gon.article.longitude
        },
        // マップの倍率はお好みで
        zoom: 17,
      });

      marker = new google.maps.Marker({
        // コントローラーで定義した変数から緯度経度を呼び出し、マーカーを立てる
        position: {
          lat: gon.article.latitude,
          lng: gon.article.longitude
        },
        map: map
      });
     }
     </script>

     <script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API'] %>&callback=initMap">
     </script>
      </div>
    </div>
  </div>
</section>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
<% if article.favorited_by?(current_user) %>
<%= link_to article_favorites_path(@article), method: :delete, remote: true do %>
<i class="fas fa-heart"></i>
<% end %>
<% else %>
<%= link_to article_favorites_path(@article), method: :post, remote: true do %>
<i class="far fa-heart"></i>
<% end %>
<% end %>
<%= @article.favorites.count %>
<% end %>

app/views/favorites/create.js.erb
<!-- favorites_buttons_< %= @barticle.id %>この部分のHTMLだけ、renderで部分的に更新するという処理です -->

$('#favorites_buttons_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {article: @article}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @article.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {article: @article}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>I LOVE ♨ゆ♨️️</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= include_gon %>
    <script src="https://kit.fontawesome.com/9856eee726.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="footerFixed">
      <div class="container-fluid">
        <div class="main-content">
        <%= render 'partial/navbar' %>
          <%= render 'partial/flash' %>
        <%= yield %>
        </div>
      </div>
      <%= render 'partial/footer' %>
    </div>
  </body>
</html>

app/views/partial/_flash.html.erb
    <!-- フラッシュメッセージ-->
    <% if flash[:notice] %>
    <div class="notification is-info">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>
    <% if flash[:alert]%>
    <div class="notification is-debger">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>

app/views/partial/_footer.html.erb
<footer>
    <span class="text-muted">©2020 StadioDig All Rights Reserved.</span>
</footer>

app/views/partial/_navbar.html.erb
<body>


 <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to articles_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">I LOVE ♨️ゆ♨</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "♨️ゆ♨️", articles_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "♨施設登録♨️️", new_article_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "♨ランキング♨️️", rank_articles_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "♨周辺施設を探す♨️️", map_articles_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class "navbar-item">
            <div class="field has-addons">
              <div class="control">
                <!--検索フォーム-->
                <%= search_form_for @search, url: search_articles_path do |f| %>
                <%= f.search_field :title_cont, autofocus: true, :placeholder => "施設を検索", class: " input is-rounded " %>
              </div>
              <div class="control">
                <%= f.submit '検索', class: 'button is-info' %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "♨️ゆ♨️", articles_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "♨ランキング♨️️", rank_articles_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "♨周辺施設を探す♨️️", map_articles_path, class: "navbar-item button is-warning is-light" %>
          </div>

          <div class "navbar-item">
            <div class="field has-addons">
              <div class="control">
                <!--検索フォーム-->
                <%= search_form_for @search, url: search_articles_path do |f| %>
                <%= f.search_field :title_cont, autofocus: true, :placeholder => "施設を検索", class: " input is-rounded " %>
              </div>
              <div class="control">
                <%= f.submit '検索', class: 'button is-info' %>
                <% end %>
              </div>
            </div>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </nav>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        プロフィール編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_with model: @user, local: true do |f| %>
          <div class="field">
            <%= f.label :name, "ユーザー名", class: "label" %>
            <%= f.text_field :name, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.email_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_area :profile, class: "textarea" %>
          </div>

          <%= f.submit "登録する", class: "button is-success" %>
          <%= link_to '退会はこちらから', out_user_path  %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/out.html.erb
<h1>Users#out</h1>
<p>Find me in app/views/users/out.html.erb</p>

<%= link_to "退会しない", user_path %>
<%= link_to "退会する", withdraw_user_path, method: :patch, data: {confirm: "本当に退会してもよろしいですか？"} %>

app/views/users/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.jpeg", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.name %></strong>
                </td>
                <% if user_signed_in? %>
                <% if @user.id == current_user.id %>
                <td>
                    <%= link_to "プロフィール編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.articles.each do |article| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to article_path(article) do %>
                  <%= attachment_image_tag article, :image, format: 'jpeg', size: "100x100", fallback: "no-image_article.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
             <div class="media">
              <div class="media-content">
                <div class="title">
                  <%= link_to article_path(article) do%>
                  <%= article.title %>
                  <% end %>
                </div>
              </div>
             </div>
              <div class="media">
                <div class="media-content">
                  <%= link_to article_path(article), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    この投稿を見る
                  <% end %>
                  <% if user_signed_in? %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_article_path(article), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      この投稿を編集する
                    <% end %>
                    <%= link_to article_path(article), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      この投稿を削除する
                    <% end %>
                  <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= article.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>